name: deploy-function

on:
  push:
    branches: [main]
    paths:
      - "functionToCosmos/**"

concurrency:
  group: deploy-function
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install
        working-directory: functionToCosmos

      - name: Build
        run: npm run build
        working-directory: functionToCosmos

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: kodaldev-functionApp
          package: functionToCosmos

  deploy-prod:
    environment: prod
    needs: deploy-dev
    name: deploy-prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install
        working-directory: functionToCosmos

      - name: Build
        run: npm run build
        working-directory: functionToCosmos

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: kodalprod-functionApp
          package: functionToCosmos
