name: deploy-api

on:
  push:
    branches: [main]
    paths:
      - "api/**"

concurrency:
  group: deploy-api
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"

      - name: Install dependencies
        run: dotnet restore api/api.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore api/api.csproj

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./publish api/api.csproj

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: kodaldev-appService
          package: ./publish

  deploy-prod:
    environment: prod
    needs: deploy-dev
    name: deploy-prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"

      - name: Install dependencies
        run: dotnet restore api/api.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore api/api.csproj

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./publish api/api.csproj

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: kodalprod-appService
          package: ./publish
